import java.sql.*;
 import javax.swing.JComboBox;
 import javax.swing.JOptionPane ;
 import javax.swing.table.DefaultTableModel;
 import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Guest
 */
public class NewJFrame11111 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame3
     */
    public NewJFrame11111() {
        initComponents();
         t5.setEnabled(false);
            t6.setEnabled(false);
            t7.setEnabled(false);
            t8.setEnabled(false);
t1.setEnabled(false);
            t2.setEnabled(false);
            t3.setEnabled(false);
            t4.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame4 = new javax.swing.JInternalFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        c1 = new javax.swing.JComboBox();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        c2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame4.setTitle("               UPDATE");
        jInternalFrame4.setPreferredSize(new java.awt.Dimension(888, 534));
        jInternalFrame4.setVisible(true);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "pno", "pname", "pquantity", "pcompany"
            }
        ));
        jScrollPane4.setViewportView(jTable5);

        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PNO", "PNAME", "PQUANTITY", "PCOMPANY", "" }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        jLabel9.setText("WHERE PR.NO IS");

        jLabel10.setText("WHERE PR NAME IS");

        jLabel11.setText("WHERE PR CLASS IS");

        jLabel12.setText("WHERE PR SUBJECT IS");

        c2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PNO", "PNAME", "PQUANTITY", "PCOMPANY", "ALL" }));
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });

        jLabel5.setText(" PR.NO CHANGE TO ");

        jLabel7.setText("PR NAME CHANGE TO");

        jLabel13.setText("PRCLASS CHANGE TO");

        jLabel8.setText("PRSUB CHANGE TO");

        javax.swing.GroupLayout jInternalFrame4Layout = new javax.swing.GroupLayout(jInternalFrame4.getContentPane());
        jInternalFrame4.getContentPane().setLayout(jInternalFrame4Layout);
        jInternalFrame4Layout.setHorizontalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame4Layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jInternalFrame4Layout.createSequentialGroup()
                        .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jInternalFrame4Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jInternalFrame4Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jInternalFrame4Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(46, 46, 46)
                                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jInternalFrame4Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(46, 46, 46)
                                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jInternalFrame4Layout.createSequentialGroup()
                                        .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel13)
                                                .addComponent(jLabel7))
                                            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(3, 3, 3)))
                                        .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(t5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(t6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jInternalFrame4Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(35, 35, 35)
                                        .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame4Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jButton3))
                    .addGroup(jInternalFrame4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 31, Short.MAX_VALUE))
        );
        jInternalFrame4Layout.setVerticalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Vijaya", 3, 24)); // NOI18N
        jLabel6.setText("TO CHANGE FUNCTION");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jInternalFrame4, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(331, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jInternalFrame4, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel my_model=(DefaultTableModel) jTable5.getModel();
        String data1 =t1.getText();
        String data2 =t2.getText();
        String data3 =t3.getText();
        String data4 =t4.getText();
        Object[]row={data1,data2,data3,data4};
        my_model.addRow(row);

        if (t1.isEnabled()&t5.isEnabled()&t6.isEnabled()&t7.isEnabled()&t8.isEnabled())
        {
            try{
                Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost/test","root","345");
                Statement stmt=con.createStatement();
                String query ="UPDATE market set pno="+t5.getText()+",pname='"+t6.getText()+"' ,pquantity="+t7.getText()+",pcompany='"+t8.getText()+"' WHERE pno="+t1.getText()+";";
                stmt.executeUpdate(query);

                stmt.close();
                con.close();
            }

            catch(Exception e) {
                JOptionPane.showMessageDialog(null,"Error in Connectivity");
            }

        }
        if (t2.isEnabled()&t5.isEnabled()&t6.isEnabled()&t7.isEnabled()&t8.isEnabled())
        {
            try{
                Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost/test","root","345");
                Statement stmt=con.createStatement();
                String query ="UPDATE market set pno="+t5.getText()+",pname='"+t6.getText()+"' ,pquantity="+t7.getText()+",pcompany='"+t8.getText()+"' WHERE pname='"+t2.getText()+"';";
                stmt.executeUpdate(query);

                stmt.close();
                con.close();
            }

            catch(Exception e) {
                JOptionPane.showMessageDialog(null,"Error in Connectivity");
            }

        }
        if (t3.isEnabled()&t5.isEnabled()&t6.isEnabled()&t7.isEnabled()&t8.isEnabled())
        {
            try{
                Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost/test","root","345");
                Statement stmt=con.createStatement();
                String query ="UPDATE market set pno="+t5.getText()+",pname='"+t6.getText()+"' ,pquantity="+t7.getText()+",pcompany='"+t8.getText()+"' WHERE pquantity="+t3.getText()+";";
                stmt.executeUpdate(query);

                stmt.close();
                con.close();
            }

            catch(Exception e) {
                JOptionPane.showMessageDialog(null,"Error in Connectivity");
            }

        }
        if (t4.isEnabled()&t5.isEnabled()&t6.isEnabled()&t7.isEnabled()&t8.isEnabled())
        {
            try{
                Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost/test","root","345");
                Statement stmt=con.createStatement();
                String query ="UPDATE market set pno="+t5.getText()+",pname='"+t6.getText()+"' ,pquantity="+t7.getText()+",pcompany='"+t8.getText()+"' WHERE pcompany='"+t4.getText()+"';";
                stmt.executeUpdate(query);

                stmt.close();
                con.close();
            }

            catch(Exception e) {
                JOptionPane.showMessageDialog(null,"Error in Connectivity");
            }

        }

        if (t1.isEnabled()&t5.isEnabled())
        {
            try{
                Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost/test","root","345");
                Statement stmt=con.createStatement();
                String query ="UPDATE market set pno="+t5.getText()+" WHERE pno="+t1.getText()+";";
                stmt.executeUpdate(query);

                stmt.close();
                con.close();
            }

            catch(Exception e) {
                JOptionPane.showMessageDialog(null,"Error in Connectivity");
            }
              if (t2.isEnabled()&t6.isEnabled())
        {
            try{
                Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost/test","root","345");
                Statement stmt=con.createStatement();
                String query ="UPDATE market set pname="+t6.getText()+" WHERE pname="+t2.getText()+";";
                stmt.executeUpdate(query);

                stmt.close();
                con.close();
            }

            catch(Exception e) {
                JOptionPane.showMessageDialog(null,"Error in Connectivity");
            }

        }
 if (t3.isEnabled()&t7.isEnabled())
        {
            try{
                Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost/test","root","345");
                Statement stmt=con.createStatement();
                String query ="UPDATE market set pquantity="+t7.getText()+" WHERE pquantity="+t3.getText()+";";
                stmt.executeUpdate(query);

                stmt.close();
                con.close();
            }

            catch(Exception e) {
                JOptionPane.showMessageDialog(null,"Error in Connectivity");
            }

        } if (t4.isEnabled()&t8.isEnabled())
        {
            try{
                Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost/test","root","345");
                Statement stmt=con.createStatement();
                String query ="UPDATE market set pompany="+t8.getText()+" WHERE pompany="+t4.getText()+";";
                stmt.executeUpdate(query);

                stmt.close();
                con.close();
            }

            catch(Exception e) {
                JOptionPane.showMessageDialog(null,"Error in Connectivity");
            }

        }
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed

        String itm=(String)c1.getSelectedItem();
        if (itm.equals ("PNO"))

        {

            t1.setEnabled(true);
            t2.setEnabled(false);
            t3.setEnabled(false);
            t4.setEnabled(false);

        }
        if (itm.equals ("PNAME"))
        {

            t2.setEnabled(true);
            t1.setEnabled(false);

            t3.setEnabled(false);
            t4.setEnabled(false);
        }
        if (itm.equals ("PQUANTITY"))
        {

            t3.setEnabled(true);
            t1.setEnabled(false);
            t2.setEnabled(false);

            t4.setEnabled(false);
        }

        if (itm.equals ("PCOMPANY"))
        {

            t4.setEnabled(true);
            t1.setEnabled(false);
            t2.setEnabled(false);
            t3.setEnabled(false);

        }
        // TODO add your handling code here:
        // int i=c1.getSelectedIndex();
        //    if (c1== SNO)

        //   String itm=(String)c1.getItemAt(i);
        //  tt2.setText(itm);

    }//GEN-LAST:event_c1ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:

        String itm=(String)c2.getSelectedItem();
        if (itm.equals ("PNO"))

        {    t5.setEnabled(true);
            t6.setEnabled(false);
            t7.setEnabled(false);
            t8.setEnabled(false);

        }
        if (itm.equals ("PNAME"))
        {
            t5.setEnabled(false);
            t6.setEnabled(true);
            t7.setEnabled(false);
            t8.setEnabled(false);

        }
        if (itm.equals ("ALL"))
        {
            t5.setEnabled(true);
            t6.setEnabled(true);
            t7.setEnabled(true);
            t8.setEnabled(true);

        }

        if (itm.equals ("PCOMPANY"))
        {
            t5.setEnabled(false);
            t6.setEnabled(false);
            t7.setEnabled(false);
            t8.setEnabled(true);

        }
         if (itm.equals ("PQUANTITY"))
        {
            t5.setEnabled(false);
            t6.setEnabled(false);
            t7.setEnabled(true);
            t8.setEnabled(false);
        }

//        } if (itm.equals ("PCOMPANY"))
//        {
//            t5.setEnabled(false);
//            t6.setEnabled(false);
//            t7.setEnabled(false);
//            t8.setEnabled(true);
//
//        } if (itm.equals ("PCOMPANY"))
//        {
//            t5.setEnabled(false);
//            t6.setEnabled(false);
//            t7.setEnabled(false);
//            t8.setEnabled(true);
//
//        } if (itm.equals ("PCOMPANY"))
//        {
//            t5.setEnabled(false);
//            t6.setEnabled(false);
//            t7.setEnabled(false);
//            t8.setEnabled(true);
//
//        }
       
    }//GEN-LAST:event_c2ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
               String i=jTextField1.getText() ;
        if(i.equals ("insert "))
        {
        new NewJFrame11().setVisible(true);
        }
        else
            if(i.equals ("delete "))
            {
                        new NewJFrame111().setVisible(true);

            }else
                 if(i.equals ("update "))
        {
        new NewJFrame11111().setVisible(true);
        }
        else
                 if(i.equals ("fetch data "))
        {
        new NewJFrame1111().setVisible(true);
        }
        else
                 if(i.equals ("start_page "))
        {
        new NewJFrameMAIN().setVisible(true);
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox c1;
    private javax.swing.JComboBox c2;
    private javax.swing.JButton jButton3;
    private javax.swing.JInternalFrame jInternalFrame4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    // End of variables declaration//GEN-END:variables
}
